# "service" is the name of this project. This will also be added to your AWS resource names.
service: awsLambda

frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1

functions:
  api:
    handler: handler.handler
    events:
      - httpApi:
          path: /
          method: get
      - httpApi:
          path: /hello
          method: get
